const root=document.getElementById('checkoutV2Root');
const toastHost=document.getElementById('checkoutV2Toast');
const SELECTION_KEY='pasar_cart_selection_v2';
const money=new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0});
const state={user:null,cart:null,selectedIds:[],stores:[],choices:{},address:null,addressEditorOpen:false,notes:{},submitting:false};

const esc=value=>String(value??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;');
const labels={seller_delivery:'Antar oleh seller',pickup:'Ambil di toko',local_courier:'Kurir lokal',cod:'COD',pay_at_store:'Bayar di toko',bank_transfer:'Transfer bank / e-wallet',merchant_qris:'QRIS merchant'};
const descriptions={seller_delivery:'Seller mengantar langsung ke lokasi kamu.',pickup:'Ambil pesanan langsung di lokasi UMKM.',local_courier:'Pesanan dikirim menggunakan kurir lokal.',cod:'Bayar saat pesanan diterima.',pay_at_store:'Bayar ketika mengambil pesanan di toko.',bank_transfer:'Bayar langsung ke rekening atau e-wallet seller setelah order dibuat.',merchant_qris:'Scan QRIS resmi milik seller setelah order dibuat.'};

function tell(message){toastHost.textContent=message;toastHost.classList.add('show');clearTimeout(tell.timer);tell.timer=setTimeout(()=>toastHost.classList.remove('show'),2600)}
async function api(path,options={}){const response=await fetch(path,{credentials:'include',cache:'no-store',...options,headers:{Accept:'application/json',...(options.body?{'Content-Type':'application/json'}:{}),...(options.headers||{})}});const data=await response.json().catch(()=>({}));if(!response.ok||data.ok===false){const error=new Error(data.error||`HTTP ${response.status}`);error.status=response.status;error.code=data.code||'';throw error}return data}
function selectedFromSession(cart){const all=(cart.items||[]).map(item=>String(item.product_id));let saved=null;try{const parsed=JSON.parse(sessionStorage.getItem(SELECTION_KEY)||'null');if(Array.isArray(parsed))saved=new Set(parsed.map(String))}catch{}if(saved===null)return all;return all.filter(id=>saved.has(id))}
function groupItems(items){const groups=new Map();for(const item of items){const id=String(item.store_id);if(!groups.has(id))groups.set(id,{store_id:id,store_name:item.store_name||'UMKM Lokal',items:[],subtotal:0});const group=groups.get(id);group.items.push(item);group.subtotal+=Number(item.price||0)*Number(item.quantity||0)}return [...groups.values()]}
function paymentOptions(settings,fulfillment){const rows=[];if(settings.cod_enabled&&fulfillment!=='pickup')rows.push('cod');if(settings.pay_at_store_enabled&&fulfillment==='pickup')rows.push('pay_at_store');if(settings.bank_transfer_enabled)rows.push('bank_transfer');if(settings.merchant_qris_enabled)rows.push('merchant_qris');return rows}
function fulfillmentOptions(settings){const candidates=[];if(settings.seller_delivery_enabled)candidates.push('seller_delivery');if(settings.pickup_enabled)candidates.push('pickup');if(settings.local_courier_enabled)candidates.push('local_courier');return candidates.filter(method=>paymentOptions(settings,method).length>0)}
function feeFor(group){const fulfillment=state.choices[group.store_id]?.fulfillment;const settings=group.settings;if(fulfillment==='pickup')return 0;if(settings.free_delivery_threshold!=null&&Number(group.subtotal)>=Number(settings.free_delivery_threshold))return 0;return Number(settings.flat_delivery_fee||0)}
function summary(){const subtotal=state.stores.reduce((sum,group)=>sum+group.subtotal,0);const shipping=state.stores.reduce((sum,group)=>sum+feeFor(group),0);return{subtotal,shipping,total:subtotal+shipping,count:state.stores.reduce((sum,group)=>sum+group.items.reduce((n,item)=>n+Number(item.quantity||0),0),0)}}
function requiresDelivery(){return state.stores.some(group=>state.choices[group.store_id]?.fulfillment!=='pickup')}
function mapLink(address=state.address){if(address?.latitude==null||address?.longitude==null)return'';return`https://www.google.com/maps?q=${Number(address.latitude)},${Number(address.longitude)}`}

function addressMarkup(){const a=state.address||{};const hasText=String(a.address_text||'').trim().length>0;const location=mapLink(a);return `<section class="cv2-section" data-cv2-address-section><div class="cv2-section-head"><h2>Alamat pengiriman</h2><button class="cv2-text-btn" type="button" data-cv2-address-edit>${state.addressEditorOpen?'Tutup':'Ubah'}</button></div><div class="cv2-address"><i class="ph ph-map-pin cv2-address-icon"></i><div class="cv2-address-copy"><div class="cv2-address-name">${esc(a.recipient_name||state.user?.name||'Penerima')} <span class="cv2-address-phone">${esc(a.phone||state.user?.phone||'')}</span></div><p class="cv2-address-text">${hasText?esc(a.address_text):'Belum ada alamat teks. Gunakan lokasi saat ini atau lengkapi alamat.'}${a.landmark?` · Patokan: ${esc(a.landmark)}`:''}</p><div class="cv2-location-line"><button type="button" class="cv2-location-chip" data-cv2-locate><i class="ph ph-crosshair"></i> Lokasi saat ini</button>${location?`<a class="cv2-map-link" href="${location}" target="_blank" rel="noopener"><i class="ph ph-map-trifold"></i> Lihat titik</a>`:''}</div></div><i class="ph ph-caret-right" aria-hidden="true"></i></div><div class="cv2-address-editor" ${state.addressEditorOpen?'':'hidden'}><div class="cv2-grid2"><div class="cv2-field"><label>Nama penerima</label><input data-address-key="recipient_name" value="${esc(a.recipient_name||state.user?.name||'')}" autocomplete="name"></div><div class="cv2-field"><label>WhatsApp / telepon</label><input data-address-key="phone" value="${esc(a.phone||state.user?.phone||'')}" inputmode="tel" autocomplete="tel"></div></div><div class="cv2-field"><label>Alamat lengkap</label><textarea data-address-key="address_text" placeholder="Nama jalan, RT/RW, kelurahan, nomor rumah...">${esc(a.address_text||'')}</textarea></div><div class="cv2-grid2"><div class="cv2-field"><label>Kecamatan</label><input data-address-key="district" value="${esc(a.district||'')}"></div><div class="cv2-field"><label>Kota</label><input data-address-key="city" value="${esc(a.city||'Lubuklinggau')}"></div></div><div class="cv2-grid2"><div class="cv2-field"><label>Provinsi</label><input data-address-key="province" value="${esc(a.province||'Sumatera Selatan')}"></div><div class="cv2-field"><label>Patokan</label><input data-address-key="landmark" value="${esc(a.landmark||'')}" placeholder="Contoh: rumah abu-abu"></div></div><button class="cv2-save-address" type="button" data-cv2-save-address>Simpan sebagai alamat utama</button></div></section>`}
function itemsMarkup(group){return `<div class="cv2-items">${group.items.map(item=>`<div class="cv2-item"><img src="${esc(item.image_url||'/assets/logo.webp')}" alt="${esc(item.name||'Produk')}" loading="lazy"><div><strong>${esc(item.name||'Produk')}</strong><small>${Number(item.quantity||0)} × ${money.format(Number(item.price||0))}</small></div><div class="cv2-item-price">${money.format(Number(item.price||0)*Number(item.quantity||0))}</div></div>`).join('')}</div>`}
function choicesMarkup(group,type){const choice=state.choices[group.store_id];const options=type==='fulfillment'?fulfillmentOptions(group.settings):paymentOptions(group.settings,choice.fulfillment);const selected=type==='fulfillment'?choice.fulfillment:choice.payment;return `<div class="cv2-choice-list">${options.map(method=>`<label class="cv2-choice"><input type="radio" name="${type}_${esc(group.store_id)}" value="${method}" data-cv2-choice="${type}" data-store-id="${esc(group.store_id)}" ${selected===method?'checked':''}><span>${esc(labels[method]||method)}</span><small>${esc(descriptions[method]||'')}</small></label>`).join('')}</div>`}
function storeMarkup(group){const verified=group.store?.verification_status==='verified';return `<section class="cv2-store" data-store="${esc(group.store_id)}"><div class="cv2-store-head"><i class="ph ph-storefront"></i><span>${esc(group.store_name)}</span>${verified?'<span class="cv2-verified"><i class="ph-fill ph-seal-check"></i> Terverifikasi</span>':''}</div>${itemsMarkup(group)}<div class="cv2-option-row"><div class="cv2-option-title"><strong>Metode pengiriman</strong></div>${choicesMarkup(group,'fulfillment')}</div><div class="cv2-option-row" data-payment-host="${esc(group.store_id)}"><div class="cv2-option-title"><strong>Metode pembayaran</strong></div>${choicesMarkup(group,'payment')}</div><div class="cv2-note-field"><input data-store-note="${esc(group.store_id)}" value="${esc(state.notes[group.store_id]||'')}" maxlength="500" placeholder="Catatan untuk ${esc(group.store_name)} · opsional"></div></section>`}
function summaryMarkup(){const s=summary();return `<section class="cv2-section"><div class="cv2-section-head"><h2>Ringkasan pesanan</h2></div><div class="cv2-summary"><div class="cv2-summary-row"><span>Subtotal produk</span><strong>${money.format(s.subtotal)}</strong></div><div class="cv2-summary-row"><span>Ongkir</span><strong>${money.format(s.shipping)}</strong></div><div class="cv2-summary-row"><span>Biaya layanan</span><strong>Rp0</strong></div><div class="cv2-summary-row total"><span>Total</span><strong>${money.format(s.total)}</strong></div></div></section>`}
function render(){const s=summary();root.innerHTML=`${addressMarkup()}${state.stores.map(storeMarkup).join('')}${summaryMarkup()}<div class="cv2-trust">Dengan membuat pesanan, kamu menyetujui transaksi langsung dengan UMKM. Pasar UMKM tidak menyimpan saldo dan tidak menahan dana pembayaran.</div>`;document.getElementById('checkoutV2Total').textContent=money.format(s.total);document.getElementById('checkoutV2Count').textContent=`Total (${s.count} item)`;const button=document.getElementById('checkoutV2Submit');button.disabled=state.submitting;button.textContent=state.submitting?'Memproses...':'Buat Pesanan'}

function updateAddressFromInput(input){const key=input.dataset.addressKey;if(!key)return;state.address={...(state.address||{}),[key]:input.value}}
function locate(){if(!navigator.geolocation){tell('Browser ini belum mendukung lokasi perangkat.');return}const buttons=[...document.querySelectorAll('[data-cv2-locate]')];buttons.forEach(button=>{button.disabled=true;button.textContent='Mencari lokasi...'});navigator.geolocation.getCurrentPosition(position=>{state.address={...(state.address||{}),latitude:Number(position.coords.latitude.toFixed(6)),longitude:Number(position.coords.longitude.toFixed(6)),accuracy_m:Math.round(position.coords.accuracy||0)};tell(`Lokasi ditemukan dengan akurasi sekitar ±${state.address.accuracy_m} m.`);render()},error=>{tell(error?.code===1?'Izin lokasi ditolak. Aktifkan izin lokasi pada browser.':'Lokasi belum dapat ditemukan. Coba kembali.');buttons.forEach(button=>{button.disabled=false;button.innerHTML='<i class="ph ph-crosshair"></i> Lokasi saat ini'})},{enableHighAccuracy:true,timeout:12000,maximumAge:30000})}
async function saveAddress(){const a=state.address||{};if(String(a.recipient_name||state.user?.name||'').trim().length<2){tell('Nama penerima belum valid.');return}if(String(a.phone||state.user?.phone||'').trim().length<5){tell('Nomor penerima belum valid.');return}if(String(a.address_text||'').trim().length<5){tell('Lengkapi alamat teks sebelum menyimpannya ke profil.');return}const payload={label:a.label||'Rumah',recipient_name:a.recipient_name||state.user?.name||'',phone:a.phone||state.user?.phone||'',address_text:a.address_text,district:a.district||'',city:a.city||'Lubuklinggau',province:a.province||'Sumatera Selatan',postal_code:a.postal_code||'',landmark:a.landmark||'',latitude:a.latitude??null,longitude:a.longitude??null,accuracy_m:a.accuracy_m??null,is_default:true};try{const path=a.id?`/api/commerce/address-book/${encodeURIComponent(a.id)}`:'/api/commerce/address-book';const data=await api(path,{method:a.id?'PATCH':'POST',body:JSON.stringify(payload)});state.address=data.address;state.addressEditorOpen=false;tell('Alamat utama disimpan.');render()}catch(error){tell(error.message||'Alamat belum dapat disimpan.')}}
function notesPayload(){return Object.fromEntries(Object.entries(state.notes).map(([key,value])=>[key,String(value||'').trim().slice(0,500)]))}
async function submit(){if(state.submitting)return;for(const group of state.stores){const choice=state.choices[group.store_id];if(!choice?.fulfillment||!choice?.payment){tell(`Pilih pengiriman dan pembayaran untuk ${group.store_name}.`);return}}const a=state.address||{};const name=String(a.recipient_name||state.user?.name||'').trim();const phone=String(a.phone||state.user?.phone||'').trim();if(name.length<2){tell('Nama penerima belum valid.');state.addressEditorOpen=true;render();return}if(phone.length<5){tell('Nomor penerima belum valid.');state.addressEditorOpen=true;render();return}const hasAddress=String(a.address_text||'').trim().length>=5;const hasGps=a.latitude!=null&&a.longitude!=null;if(requiresDelivery()&&!hasAddress&&!hasGps){tell('Pesanan yang diantar membutuhkan alamat atau titik lokasi saat ini.');state.addressEditorOpen=true;render();return}state.submitting=true;render();try{const preferences=state.stores.map(group=>({store_id:group.store_id,fulfillment_method:state.choices[group.store_id].fulfillment,payment_method:state.choices[group.store_id].payment,delivery_district:a.district||'',delivery_city:a.city||'Lubuklinggau'}));await api('/api/commerce/checkout/preferences',{method:'PUT',body:JSON.stringify({preferences})});const result=await api('/api/commerce/checkout-v2',{method:'POST',body:JSON.stringify({selected_product_ids:state.selectedIds,customer_name:name,customer_phone:phone,delivery_address:a.address_text||'',delivery_latitude:a.latitude??null,delivery_longitude:a.longitude??null,delivery_accuracy_m:a.accuracy_m??null,delivery_landmark:a.landmark||'',notes_by_store:notesPayload()})});sessionStorage.removeItem(SELECTION_KEY);tell(`${result.count||1} pesanan berhasil dibuat.`);setTimeout(()=>location.replace('/purchases/'),450)}catch(error){state.submitting=false;tell(error.message||'Pesanan belum dapat dibuat.');render()}}

async function init(){try{const [meData,cartData,addressData]=await Promise.all([api('/api/auth/me'),api('/api/commerce/cart'),api('/api/commerce/address-book').catch(()=>({default_address:null}))]);state.user=meData.user||meData;state.cart=cartData.cart||{};state.selectedIds=selectedFromSession(state.cart);if(!state.selectedIds.length){root.innerHTML='<div class="cv2-empty"><strong>Tidak ada produk yang dipilih.</strong><p>Kembali ke keranjang dan centang produk yang ingin dibeli.</p><a href="/">Kembali ke Pasar</a></div>';document.getElementById('checkoutV2Submit').disabled=true;return}const selectedSet=new Set(state.selectedIds);const selectedItems=(state.cart.items||[]).filter(item=>selectedSet.has(String(item.product_id)));if(selectedItems.length!==state.selectedIds.length){throw new Error('Pilihan keranjang berubah. Kembali ke keranjang untuk memeriksa produk.')}state.address=addressData.default_address||{recipient_name:state.user?.name||'',phone:state.user?.phone||'',address_text:'',district:'',city:'Lubuklinggau',province:'Sumatera Selatan',landmark:'',latitude:null,longitude:null,accuracy_m:null};const groups=groupItems(selectedItems);state.stores=await Promise.all(groups.map(async group=>{const data=await api(`/api/commerce/fulfillment/stores/${encodeURIComponent(group.store_id)}`);const merged={...group,store:data.store||{},settings:data.settings||{}};const fulfillments=fulfillmentOptions(merged.settings);if(!fulfillments.length)throw new Error(`${group.store_name} belum memiliki kombinasi pengiriman dan pembayaran yang dapat digunakan.`);const fulfillment=fulfillments[0];const payments=paymentOptions(merged.settings,fulfillment);state.choices[group.store_id]={fulfillment,payment:payments[0]};state.notes[group.store_id]='';return merged}));render()}catch(error){if(error.status===401){location.replace('/?intent=login');return}root.innerHTML=`<div class="cv2-empty"><strong>Checkout belum dapat dibuka.</strong><p>${esc(error.message||'Terjadi kendala saat memuat checkout.')}</p><a href="/">Kembali ke Pasar</a></div>`;document.getElementById('checkoutV2Submit').disabled=true}}

root.addEventListener('input',event=>{if(event.target.matches('[data-address-key]'))updateAddressFromInput(event.target);const store=event.target.dataset.storeNote;if(store)state.notes[store]=event.target.value});
root.addEventListener('change',event=>{const input=event.target.closest('[data-cv2-choice]');if(!input)return;const storeId=String(input.dataset.storeId||'');const group=state.stores.find(item=>item.store_id===storeId);if(!group)return;if(input.dataset.cv2Choice==='fulfillment'){state.choices[storeId].fulfillment=input.value;const payments=paymentOptions(group.settings,input.value);if(!payments.includes(state.choices[storeId].payment))state.choices[storeId].payment=payments[0]||'';render();return}state.choices[storeId].payment=input.value});
root.addEventListener('click',event=>{if(event.target.closest('[data-cv2-address-edit]')){state.addressEditorOpen=!state.addressEditorOpen;render();return}if(event.target.closest('[data-cv2-locate]')){locate();return}if(event.target.closest('[data-cv2-save-address]'))saveAddress()});
document.getElementById('checkoutV2Submit').addEventListener('click',submit);
init();
