'use strict';
(()=>{
if(window.PasarPerformanceV10?.version==='10.1')return;
const doc=document,u=doc.createElement('script');u.src='js/ui-consistency-v1.js?v=1.0';u.async=false;doc.head.append(u);
const jobs=new Map(),replaying=new WeakSet(),publicPaths=new Set(['/api/categories','/api/stores','/api/products','/api/posts']),responseCache=new Map();
const PUBLIC_CACHE_TTL_MS=20_000;
const PUBLIC_CACHE_MAX_ENTRIES = 64;
const INTENT_LOAD_TIMEOUT_MS=4_500;
let warmRequests=0,replayCount=0,lazyLoads=0,intentTimeouts=0,lcp=0,cls=0,longTasks=0;
const ASSETS=Object.freeze({efficiency: 'js/performance-v10-b.js?v=7a5a0101a671',stability: 'js/performance-v10-c.js?v=e289ccfe89b5',chat: 'js/chat-single-render-v6.js?v=ef079b1c35ef',commerce: 'js/p8-commerce-integration.js?v=fc3dcbac9b78',account: 'js/account-resilience.js?v=05a13489b947&seller=1',saved: 'js/profile-saved.js?v=fbf14ea3f0cd',reels: 'js/reels-v4-entry.js?v=5277c6ed5d67'});
function capability(){const connection=navigator.connection||navigator.mozConnection||navigator.webkitConnection||null,effectiveType=String(connection?.effectiveType||'').toLowerCase(),saveData=Boolean(connection?.saveData),cores=Number(navigator.hardwareConcurrency||0),memory=Number(navigator.deviceMemory||0),constrained=saveData||['slow-2g','2g'].includes(effectiveType),lowEnd=(cores>0&&cores<=4)||(memory>0&&memory<=4);return Object.freeze({effectiveType,saveData,cores,memory,constrained,lowEnd})}
function publicKey(input,init){try{const request=input instanceof Request?input:new Request(input,init),url=new URL(request.url,location.href);if(url.origin!==location.origin||String(request.method||'GET').toUpperCase()!=='GET')return null;return publicPaths.has(url.pathname)?`${url.pathname}${url.search}`:null}catch{return null}}
const rawFetch=window.fetch.bind(window);
window.fetch=async function v10Fetch(input,init){const key=publicKey(input,init);if(!key)return rawFetch(input,init);const now=Date.now(),cached=responseCache.get(key);if(cached?.expiresAt > now){try{return(await cached.promise).clone()}catch{responseCache.delete(key)}}else if (cached) responseCache.delete(key);if(responseCache.size >= PUBLIC_CACHE_MAX_ENTRIES)responseCache.delete(responseCache.keys().next().value);warmRequests += 1;const promise=rawFetch(input,init).then(response=>{if(!response.ok)responseCache.delete(key);return response}).catch(error=>{responseCache.delete(key);throw error});responseCache.set(key,{expiresAt:now+PUBLIC_CACHE_TTL_MS,promise});return(await promise).clone()};
function loadScript(name,ready){if(ready?.())return Promise.resolve(ready());if(jobs.has(name))return jobs.get(name);const src=ASSETS[name];if(!src)return Promise.reject(new Error(`Unknown V10 asset: ${name}`));const job=new Promise((resolve,reject)=>{const script=doc.createElement('script');script.src=src;script.async=true;script.dataset.v10Lazy=name;script.onload=()=>{lazyLoads+=1;resolve(ready?.()||true)};script.onerror=()=>reject(new Error(`Gagal memuat ${name}.`));doc.body.appendChild(script)}).catch(error=>{jobs.delete(name);throw error});jobs.set(name,job);return job}
function waitForReady(ready,label,timeout=4000){const initial=ready();if(initial)return Promise.resolve(initial);return new Promise((resolve,reject)=>{const deadline=Date.now()+timeout,poll=()=>{const value=ready();if(value){resolve(value);return}if(Date.now()>=deadline){reject(new Error(`${label} runtime timeout.`));return}setTimeout(poll,50)};poll()})}
const loaders=Object.freeze({efficiency:()=>loadScript('efficiency',()=>window.PasarPerformanceV10B?.version==='10.2'),stability: () => loadScript('stability',()=>window.PasarPerformanceV10C?.version==='10.3'),chat:()=>loadScript('chat',()=>typeof window.ensurePasarChatV7==='function'),commerce:()=>loadScript('commerce',()=>window.PasarP8Commerce?.version==='1.2'),account:()=>loadScript('account',()=>window.PasarP6Loader?.version==='1.1'),saved:()=>loadScript('saved',()=>typeof window.hydratePersistentSaved==='function'),reels:()=>loadScript('reels',()=>window.PasarReelsV4?.version==='4.0').then(()=>waitForReady(()=>window.PasarReelsV4?.version==='4.0'?window.PasarReelsV4:null,'reels'))});
function withIntentTimeout(promise,label){let timer=0;return Promise.race([promise,new Promise((_,reject)=>{timer=setTimeout(()=>{intentTimeouts+=1;reject(new Error(`${label} bootstrap timeout.`))},INTENT_LOAD_TIMEOUT_MS)})]).finally(()=>clearTimeout(timer))}
function installIntentGate({selector,ready,loader,label,fallback,root=doc}){const prewarm=event=>{const target=event.target?.closest?.(selector);if(target&&!ready())loader().catch(()=>null)};root.addEventListener('pointerdown',prewarm,{capture:true,passive:true});root.addEventListener('focusin',prewarm,true);root.addEventListener('click',async event=>{const target=event.target?.closest?.(selector);if(!target||ready()||replaying.has(target))return;event.preventDefault();event.stopImmediatePropagation();target.setAttribute('aria-busy','true');try{await withIntentTimeout(loader(),label);replayCount+=1;replaying.add(target);target.click();queueMicrotask(()=>replaying.delete(target))}catch(error){console.error(`[Pasar UMKM] V10 ${label} bootstrap error:`,error);if(typeof fallback==='function'&&fallback(target,error)===true)return;window.showToast?.('Fitur belum dapat dibuka. Coba lagi.')}finally{target.removeAttribute('aria-busy')}},true)}
doc.addEventListener('click',e=>e.target.closest('[data-nav=reels]')&&loaders.reels(),true);
installIntentGate({selector:'[data-action="messages"],[data-social-action="message-user"],[data-social-action="open-conversation"]',ready:()=>typeof window.ensurePasarChatV7==='function',loader:loaders.chat,label:'chat'});
installIntentGate({selector:['[data-action="buy-now"]','[data-commerce-action="buy-now"]','[data-cart-v2-checkout]','[data-action="checkout"]','[data-function-action="checkout-open"]','[data-commerce-action="checkout"]','[data-action="post-create"]','[data-nav="cart"]','[data-nav="account"]','.post-card.is-product-post .ig-product-media','.post-card[data-post-id^="post-"] .ig-product-media'].join(','),ready:()=>window.PasarP8Commerce?.version==='1.2',loader:loaders.commerce,label:'commerce',fallback:target=>{const checkout=target.matches?.('[data-cart-v2-checkout],[data-action="checkout"],[data-function-action="checkout-open"],[data-commerce-action="checkout"]');if(!checkout)return false;location.assign('/checkout/index.html');return true}});
installIntentGate({selector:['[data-nav="account"]','[data-action="account-edit"]','[data-action="notifications"]','[data-action="comments"]','[data-action="like"]','[data-action="save"]','[data-action="seller-profile"]','[data-menu-action="favorites"]','[data-action="open-story"]','[data-action="add-story"]','[data-menu-action="business-agency"]','[data-function-action="business-agency"]'].join(','),ready:()=>window.PasarP6Loader?.version==='1.1',loader:loaders.account,label:'account'});
installIntentGate({selector:'[data-menu-action="favorites"],[data-action="save"],[data-nav="account"]',ready:()=>typeof window.hydratePersistentSaved==='function',loader:loaders.saved,label:'saved'});
function observeVitals(){if(!('PerformanceObserver'in window))return;try{new PerformanceObserver(list=>{const entries=list.getEntries(),last=entries[entries.length-1];if(last)lcp=Math.round(last.startTime||0)}).observe({type:'largest-contentful-paint',buffered:true})}catch{}try{new PerformanceObserver(list=>{for(const entry of list.getEntries())if(!entry.hadRecentInput)cls+=Number(entry.value||0)}).observe({type:'layout-shift',buffered:true})}catch{}try{new PerformanceObserver(list=>{longTasks+=list.getEntries().length}).observe({type:'longtask',buffered:true})}catch{}}
function runWhenIdle(task,timeout=3000,fallbackDelay=1200){if('requestIdleCallback'in window){requestIdleCallback(()=>task(),{timeout});return}setTimeout(task,fallbackDelay)}
function afterWindowLoad(task){const run=()=>task();if(doc.readyState==='complete')run();else window.addEventListener('load',run,{once:true,passive:true})}
function scheduleEfficiency(){afterWindowLoad(()=>{if(doc.visibilityState==='hidden')return;runWhenIdle(()=>{loaders.efficiency().catch(error=>console.warn('[Pasar UMKM] V10 efficiency bootstrap:',error));runWhenIdle(()=>loaders.stability().catch(error=>console.warn('[Pasar UMKM] V10 stability bootstrap:',error)),5000,1800)},3500,900)})}
function scheduleWarmup(){afterWindowLoad(()=>{if(doc.visibilityState==='hidden')return;const device=capability();if(device.constrained||device.lowEnd||device.effectiveType==='3g')return;runWhenIdle(()=>loaders.saved().catch(()=>null),6500,3200)})}
observeVitals();scheduleEfficiency();scheduleWarmup();
window.PasarP2Performance=Object.freeze({version:'2.0',networkCapability:capability,getDiagnostics:()=>Object.freeze({warm_requests: warmRequests,cache_entries:responseCache.size,network:capability()})});
window.PasarPerformanceV10=Object.freeze({version:'10.1',capability,clearPublicCache:()=>responseCache.clear(),openReels:()=>loaders.reels().then(reels=>reels.open()).catch(error=>{console.error('[Pasar UMKM] Reels navigation error:',error);window.showToast?.('Reels belum dapat dibuka. Coba lagi.')}),load:name=>loaders[name]?.()||Promise.reject(new Error(`Unknown V10 feature: ${name}`)),getDiagnostics:()=>Object.freeze({capability:capability(),warm_requests: warmRequests,cache_entries:responseCache.size,lazy_loads:lazyLoads,replayed_intents:replayCount,intent_timeouts: intentTimeouts,lcp_ms:lcp,cls:Number(cls.toFixed(4)),long_tasks:longTasks})});
})();
