import { adminApi } from "./api.js?v=7.0.0";

const number = new Intl.NumberFormat("id-ID");
const STATUS_LABELS = Object.freeze({ draft:"Draf", scheduled:"Terjadwal", active:"Aktif", paused:"Dijeda", ended:"Berakhir" });
function esc(value){return String(value??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;")}
function metric(label,value,detail=""){return `<div class="metric-item"><span class="metric-label">${esc(label)}</span><span class="metric-value">${esc(value)}</span>${detail?`<span class="metric-detail">${esc(detail)}</span>`:""}</div>`}
function status(value){const key=String(value||"draft");const tone=key==="active"?"status-success":key==="ended"?"status-info":key==="paused"?"status-warning":"status-info";return `<span class="status ${tone}">${esc(STATUS_LABELS[key]||key)}</span>`}

function promotionForm(){return `<section class="section-block"><div class="section-head"><div><h2 class="section-title">Buat placement promosi</h2><p class="section-copy">Atur slot promosi organik atau sponsor tanpa billing, saldo, atau settlement di dalam platform.</p></div></div><form class="form-stack" id="promotionForm"><div class="field-group"><label class="field-label">Placement</label><select class="field-input" name="placement"><option value="home_featured">Beranda unggulan</option><option value="search_boost">Dorongan pencarian</option><option value="store_featured">Toko unggulan</option><option value="sponsor_banner">Banner sponsor</option></select></div><div class="field-group"><label class="field-label">Jenis target</label><select class="field-input" name="subject_type"><option value="product">Produk</option><option value="store">Toko</option><option value="post">Konten</option><option value="external">Tautan eksternal</option></select></div><div class="field-group"><label class="field-label">ID target</label><input class="field-input" name="subject_id" placeholder="UUID produk, toko, atau konten. Kosongkan untuk eksternal."></div><div class="field-group"><label class="field-label">ID toko <span class="field-hint">opsional</span></label><input class="field-input" name="store_id" placeholder="UUID toko"></div><div class="field-group"><label class="field-label">Judul promosi</label><input class="field-input" name="headline" maxlength="180" placeholder="Judul singkat yang tampil pada placement"></div><div class="field-group"><label class="field-label">Label sponsor</label><input class="field-input" name="sponsor_label" maxlength="120" placeholder="Nama sponsor atau mitra"></div><div class="field-group"><label class="field-label">URL tujuan</label><input class="field-input" name="destination_url" maxlength="800" placeholder="https://…"></div><div class="field-group"><label class="field-label">Status awal</label><select class="field-input" name="status"><option value="draft">Draf</option><option value="scheduled">Terjadwal</option><option value="active">Aktif</option><option value="paused">Dijeda</option></select></div><div class="field-group"><label class="field-label">Mulai</label><input class="field-input" type="datetime-local" name="starts_at"></div><div class="field-group"><label class="field-label">Berakhir</label><input class="field-input" type="datetime-local" name="ends_at"></div><button class="button button-primary" type="submit">Simpan placement</button></form></section>`}

function promotionRows(items, canManage){if(!items.length)return `<div class="empty-state"><strong>Belum ada placement promosi.</strong><p>Registry promosi masih kosong.</p></div>`;return `<div class="data-shell">${items.map(item=>`<article class="data-row"><div class="row-main"><div class="row-title"><strong>${esc(item.headline||item.placement)}</strong>${status(item.status)}</div><div class="row-meta"><span>${esc(item.placement)}</span><span>${esc(item.subject_type)}${item.subject_id?` · ${esc(item.subject_id)}`:""}</span>${item.store_name?`<span>${esc(item.store_name)}</span>`:""}</div></div><div></div>${canManage?`<div class="row-actions"><button type="button" class="row-action row-action-positive" data-promo-status="active" data-promo-id="${esc(item.id)}">Aktifkan</button><button type="button" class="row-action" data-promo-status="paused" data-promo-id="${esc(item.id)}">Jeda</button><button type="button" class="row-action row-action-danger" data-promo-status="ended" data-promo-id="${esc(item.id)}">Akhiri</button></div>`:""}</article>`).join("")}</div>`}

export async function renderGrowth({ host, permissionSet, signal, confirmAction, refresh }) {
  const canViewPromotions = permissionSet.has("promotions.view");
  const canManage = permissionSet.has("promotions.manage");
  const [metricPayload,promotionPayload] = await Promise.all([
    adminApi.growthMetrics({ signal }),
    canViewPromotions ? adminApi.promotions({}, { signal }) : Promise.resolve({ promotions:[] })
  ]);
  const m = metricPayload.metrics || {};
  const promotions = promotionPayload.promotions || [];
  host.innerHTML = `<header class="view-header"><div><p class="eyebrow">Pertumbuhan marketplace</p><h1 class="view-title">Analitik & promosi</h1><p class="view-description">Pantau funnel dari event yang benar-benar terinstrumentasi. Data sebelum rollout P7 tidak direkonstruksi atau dikarang.</p></div><div class="view-actions"><a class="button button-secondary" href="/launch/" target="_blank" rel="noopener">Pusat Launch Seller</a></div></header><section class="metric-strip" aria-label="Funnel 7 hari">${metric("Pengunjung 7 hari",number.format(m.visitors_7d||0),`${number.format(m.page_views_7d||0)} page view`)}${metric("Dilihat → keranjang",number.format(m.product_views_7d||0),`${m.product_to_cart_7d_pct||0}% masuk keranjang`)}${metric("Keranjang → checkout",number.format(m.add_to_cart_7d||0),`${m.cart_to_checkout_7d_pct||0}% mulai checkout`)}${metric("Checkout → selesai",number.format(m.checkout_started_7d||0),`${m.checkout_to_completed_7d_pct||0}% selesai`)}</section><section class="section-block"><div class="section-head"><div><h2 class="section-title">Funnel 30 hari</h2><p class="section-copy">Conversion dihitung hanya dari event yang benar-benar tercatat setelah instrumentation aktif.</p></div></div><ul class="access-list"><li class="access-item"><div class="access-name"><strong>Pengunjung</strong><span>Pengguna unik atau hash anonim</span></div><strong>${number.format(m.visitors_30d||0)}</strong></li><li class="access-item"><div class="access-name"><strong>Produk → keranjang</strong><span>${number.format(m.product_views_30d||0)} product view</span></div><strong>${m.product_to_cart_30d_pct||0}%</strong></li><li class="access-item"><div class="access-name"><strong>Keranjang → checkout</strong><span>${number.format(m.add_to_cart_30d||0)} add-to-cart</span></div><strong>${m.cart_to_checkout_30d_pct||0}%</strong></li><li class="access-item"><div class="access-name"><strong>Checkout → selesai</strong><span>${number.format(m.checkout_started_30d||0)} checkout dimulai</span></div><strong>${m.checkout_to_completed_30d_pct||0}%</strong></li></ul></section>${canViewPromotions?`<section class="section-block"><div class="section-head"><div><h2 class="section-title">Placement promosi</h2><p class="section-copy">Registry featured dan search placement. Billing tetap berada di luar scope modul ini.</p></div></div>${promotionRows(promotions,canManage)}</section>`:""}${canManage?promotionForm():""}<section class="security-note"><div><strong>Analitik minim data pribadi</strong><p>Growth event tidak menyimpan raw IP atau raw user-agent. Anonymous browser key di-hash server-side.</p></div></section>`;

  document.getElementById("promotionForm")?.addEventListener("submit", async event => {
    event.preventDefault();
    const button = event.currentTarget.querySelector("button[type=submit]");
    button.disabled = true;
    try {
      const raw = Object.fromEntries(new FormData(event.currentTarget).entries());
      const payload = { ...raw, starts_at: raw.starts_at ? new Date(raw.starts_at).toISOString() : null, ends_at: raw.ends_at ? new Date(raw.ends_at).toISOString() : null };
      await adminApi.createPromotion(payload);
      await refresh();
    } finally { button.disabled = false; }
  });

  host.querySelectorAll("[data-promo-status]").forEach(button => button.addEventListener("click", async () => {
    const nextLabel = STATUS_LABELS[button.dataset.promoStatus] || button.dataset.promoStatus;
    const reason = await confirmAction({ title:"Ubah status promosi", copy:`Ubah placement menjadi ${nextLabel}?`, confirmLabel:"Simpan status", tone:button.dataset.promoStatus==='ended'?"danger":"positive", requireReason:true });
    if (!reason) return;
    button.disabled = true;
    try { await adminApi.changePromotionStatus(button.dataset.promoId, button.dataset.promoStatus, reason); await refresh(); }
    finally { button.disabled = false; }
  }));
}
