-- =========================================================
-- PASAR UMKM - CUSTOMER SUPPORT V1
-- 2026-09-09
--
-- Additive launch-hardening migration:
-- 1. Private user <-> platform support tickets.
-- 2. Support messages, evidence images, and internal admin notes.
-- 3. Explicit admin RBAC capabilities for support agents.
-- 4. Read/unread timestamps and operational indexes.
--
-- No existing marketplace/chat/order table is mutated.
-- =========================================================

DO $$
BEGIN
  IF to_regclass('public.users') IS NULL
     OR to_regclass('public.orders') IS NULL
     OR to_regclass('public.stores') IS NULL
     OR to_regclass('public.admin_accounts') IS NULL
     OR to_regclass('public.admin_roles') IS NULL
     OR to_regclass('public.admin_permissions') IS NULL
     OR to_regclass('public.admin_role_permissions') IS NULL
     OR to_regclass('public.schema_migrations') IS NULL THEN
    RAISE EXCEPTION 'Customer Support V1 migration ditolak: dependency schema belum lengkap.';
  END IF;
END $$;

CREATE TABLE IF NOT EXISTS support_tickets (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  ticket_no BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  category VARCHAR(32) NOT NULL CHECK (category IN (
    'order','payment','account_security','seller_verification','product_report','complaint','other'
  )),
  subject VARCHAR(140) NOT NULL CHECK (char_length(btrim(subject)) BETWEEN 4 AND 140),
  status VARCHAR(24) NOT NULL DEFAULT 'waiting_support' CHECK (status IN (
    'waiting_support','in_progress','waiting_user','resolved','closed'
  )),
  priority VARCHAR(12) NOT NULL DEFAULT 'normal' CHECK (priority IN ('low','normal','high','urgent')),
  order_id UUID NULL REFERENCES orders(id) ON DELETE SET NULL,
  store_id UUID NULL REFERENCES stores(id) ON DELETE SET NULL,
  assigned_admin_id UUID NULL REFERENCES admin_accounts(id) ON DELETE SET NULL,
  user_last_read_at TIMESTAMPTZ NULL,
  admin_last_read_at TIMESTAMPTZ NULL,
  last_user_message_at TIMESTAMPTZ NULL,
  last_admin_message_at TIMESTAMPTZ NULL,
  resolved_at TIMESTAMPTZ NULL,
  closed_at TIMESTAMPTZ NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS support_messages (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  ticket_id UUID NOT NULL REFERENCES support_tickets(id) ON DELETE CASCADE,
  sender_type VARCHAR(12) NOT NULL CHECK (sender_type IN ('user','admin','system')),
  user_id UUID NULL REFERENCES users(id) ON DELETE SET NULL,
  admin_account_id UUID NULL REFERENCES admin_accounts(id) ON DELETE SET NULL,
  message TEXT NULL CHECK (message IS NULL OR char_length(message) <= 4000),
  media_type VARCHAR(12) NULL CHECK (media_type IS NULL OR media_type = 'image'),
  media_url TEXT NULL,
  media_name VARCHAR(180) NULL,
  media_bytes INTEGER NULL CHECK (media_bytes IS NULL OR media_bytes > 0),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT support_message_actor_ck CHECK (
    (sender_type = 'user' AND user_id IS NOT NULL AND admin_account_id IS NULL)
    OR (sender_type = 'admin' AND user_id IS NULL AND admin_account_id IS NOT NULL)
    OR (sender_type = 'system' AND user_id IS NULL AND admin_account_id IS NULL)
  ),
  CONSTRAINT support_message_content_ck CHECK (
    NULLIF(btrim(COALESCE(message, '')), '') IS NOT NULL OR media_url IS NOT NULL
  )
);

CREATE TABLE IF NOT EXISTS support_internal_notes (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  ticket_id UUID NOT NULL REFERENCES support_tickets(id) ON DELETE CASCADE,
  admin_account_id UUID NOT NULL REFERENCES admin_accounts(id) ON DELETE RESTRICT,
  note TEXT NOT NULL CHECK (char_length(btrim(note)) BETWEEN 2 AND 4000),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS support_ticket_events (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  ticket_id UUID NOT NULL REFERENCES support_tickets(id) ON DELETE CASCADE,
  actor_type VARCHAR(12) NOT NULL CHECK (actor_type IN ('user','admin','system')),
  user_id UUID NULL REFERENCES users(id) ON DELETE SET NULL,
  admin_account_id UUID NULL REFERENCES admin_accounts(id) ON DELETE SET NULL,
  event_type VARCHAR(40) NOT NULL,
  from_value TEXT NULL,
  to_value TEXT NULL,
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT support_event_actor_ck CHECK (
    (actor_type = 'user' AND user_id IS NOT NULL AND admin_account_id IS NULL)
    OR (actor_type = 'admin' AND user_id IS NULL AND admin_account_id IS NOT NULL)
    OR (actor_type = 'system' AND user_id IS NULL AND admin_account_id IS NULL)
  )
);

CREATE INDEX IF NOT EXISTS support_tickets_user_updated_idx
  ON support_tickets(user_id, updated_at DESC, id DESC);
CREATE INDEX IF NOT EXISTS support_tickets_status_updated_idx
  ON support_tickets(status, updated_at DESC, id DESC);
CREATE INDEX IF NOT EXISTS support_tickets_admin_queue_idx
  ON support_tickets(priority, updated_at DESC, id DESC)
  WHERE status IN ('waiting_support','in_progress','waiting_user');
CREATE INDEX IF NOT EXISTS support_tickets_assignee_idx
  ON support_tickets(assigned_admin_id, updated_at DESC)
  WHERE assigned_admin_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS support_messages_ticket_created_idx
  ON support_messages(ticket_id, created_at ASC, id ASC);
CREATE INDEX IF NOT EXISTS support_notes_ticket_created_idx
  ON support_internal_notes(ticket_id, created_at DESC, id DESC);
CREATE INDEX IF NOT EXISTS support_events_ticket_created_idx
  ON support_ticket_events(ticket_id, created_at DESC, id DESC);

INSERT INTO admin_permissions (
  permission_key, resource, action, description, is_sensitive, is_active
)
VALUES
  ('support.view', 'support', 'view', 'View customer-support queues and ticket context.', FALSE, TRUE),
  ('support.reply', 'support', 'reply', 'Reply to customer-support conversations.', FALSE, TRUE),
  ('support.manage', 'support', 'manage', 'Assign, prioritize, resolve, reopen, and annotate support tickets.', TRUE, TRUE)
ON CONFLICT (permission_key) DO UPDATE SET
  resource = EXCLUDED.resource,
  action = EXCLUDED.action,
  description = EXCLUDED.description,
  is_sensitive = EXCLUDED.is_sensitive,
  is_active = TRUE;

-- Super Admin remains explicit-permission based. New capabilities are granted,
-- never bypassed in application code.
INSERT INTO admin_role_permissions (role_id, permission_id, granted_by_admin_id)
SELECT ar.id, ap.id, NULL
FROM admin_roles ar
JOIN admin_permissions ap ON ap.permission_key IN ('support.view','support.reply','support.manage')
WHERE ar.role_key = 'super_admin' AND ar.is_active = TRUE AND ap.is_active = TRUE
ON CONFLICT (role_id, permission_id) DO NOTHING;

-- Dedicated Support role gets the customer-support workspace without account,
-- system, suspension, or financial powers.
INSERT INTO admin_role_permissions (role_id, permission_id, granted_by_admin_id)
SELECT ar.id, ap.id, NULL
FROM admin_roles ar
JOIN admin_permissions ap ON ap.permission_key IN ('support.view','support.reply','support.manage')
WHERE ar.role_key = 'support' AND ar.is_active = TRUE AND ap.is_active = TRUE
ON CONFLICT (role_id, permission_id) DO NOTHING;

INSERT INTO schema_migrations(version, description)
VALUES (
  '2026-09-09-customer-support-v1',
  'Private customer-support tickets, messages, evidence, internal notes, read state, queue indexes, and explicit support RBAC.'
)
ON CONFLICT (version) DO UPDATE SET description = EXCLUDED.description;
